version: '3'
services:
  api_server:
    image: api_server
    container_name: api_server
    build: ./api_server
    command: node index.js
    ports:
      - '8081:8081'
    depends_on:
      - 'mongo'

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  dashboard:
    image: dashboard
    container_name: dashboard
    build: ./dashboard
    command: node server.js
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
      - 'api_server'